name: Test Qt Deployment on Windows

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test-windeployqt:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Install Qt and Qt tools using Chocolatey
    - name: Install Qt and Qt Tools (Windows)
      run: |
        choco install qt6-default qt6-tools
    shell: cmd

    # Locate and log windeployqt
    - name: Locate windeployqt
      run: |
        $windeployqt = Get-Command -ErrorAction SilentlyContinue -Name "windeployqt.exe"
        if (-not $windeployqt) {
          $qtPath = Get-ChildItem -Recurse -Filter windeployqt.exe "C:\Qt\" | Select-Object -First 1
          if (-not $qtPath) {
            Write-Error "windeployqt.exe not found. Installation failed or windeployqt is missing."
            exit 1
          }
          echo "windeployqt found at: $($qtPath.FullName)"
        } else {
          echo "windeployqt already in PATH."
        }
    shell: pwsh
