name: Build and Release Static Binaries

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  # ----------- Linux Build -----------
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Cache CMake Build
      uses: actions/cache@v3
      with:
        path: build
        key: cmake-build-${{ runner.os }}-${{ github.ref }}
        restore-keys: |
          cmake-build-${{ runner.os }}-

    - name: Install Dependencies
      run: |
        apt update
        apt install -y ninja-build build-essential libgl1-mesa-dev libglu1-mesa-dev rsync \
        qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools wget

    - name: Download and Setup linuxdeployqt
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        mv linuxdeployqt-continuous-x86_64.AppImage /usr/local/bin/linuxdeployqt

    - name: Configure and Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G 'Ninja' -S .
        cmake --build build --config Release

    - name: Package AppImage
      run: |
        linuxdeployqt build/Forex-Calculator -appimage
        mkdir -p artifacts
        mv Forex-Calculator*.AppImage artifacts/Forex-Calculator_linux.AppImage

    - name: Upload Artifact (Linux)
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_linux
        path: artifacts/Forex-Calculator_linux.AppImage

  # ----------- macOS Build -----------
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Cache CMake Build
      uses: actions/cache@v3
      with:
        path: build
        key: cmake-build-${{ runner.os }}-${{ github.ref }}
        restore-keys: |
          cmake-build-${{ runner.os }}-

    - name: Install Dependencies (macOS)
      run: brew install ninja qt

    - name: Configure CMake (macOS)
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release \
          -G "Ninja" \
          -S .
    
    - name: Build Forex-Calculator (macOS)
      run: cmake --build build --config Release

    - name: Package Forex-Calculator (macOS)
      run: |
        mkdir -p artifacts
        zip -r artifacts/Forex-Calculator_macos.zip build

    - name: Upload Artifact (macOS)
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_macos
        path: artifacts/Forex-Calculator_macos.zip

  # ----------- Windows Build -----------
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Cache Qt Installation
      uses: actions/cache@v3
      with:
        path: D:\a\
        key: qt-install-${{ runner.os }}-${{ github.ref }}
        restore-keys: |
          qt-install-${{ runner.os }}-

    - name: Install Dependencies (Windows)
      run: |
        choco install ninja cmake mingw
      shell: cmd

    - name: Install Qt (Windows)
      if: steps.cache.outputs.cache-hit != 'true'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'

    - name: Configure CMake (Windows)
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release ^
          -G Ninja ^
          -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" ^
          -S .
      shell: cmd

    - name: Build Forex-Calculator (Windows)
      run: cmake --build build --config Release
      shell: cmd

    - name: Deploy Qt DLLs (Windows)
      run: |
        $windeployqt = Get-ChildItem -Recurse -Filter windeployqt.exe "D:\a\" | Select-Object -First 1
        if ($windeployqt) {
          Write-Host "windeployqt found at: $($windeployqt.FullName)"
          & "$($windeployqt.FullName)" --dir build build\Forex-Calculator.exe
        } else {
          Write-Error "windeployqt.exe not found. Qt installation or PATH may be incorrect."
          exit 1
        }
      shell: pwsh

    - name: Package Forex-Calculator (Windows)
      run: |
        mkdir -p artifacts
        Compress-Archive -Path "build/*" -DestinationPath "artifacts/Forex-Calculator_windows.zip"
      shell: pwsh

    - name: Upload Artifact (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_windows
        path: artifacts/Forex-Calculator_windows.zip

  # ----------- Release Job -----------
  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List Downloaded Files
      run: ls -R artifacts

    - name: Generate Tag Name
      id: tag_name
      run: echo "RELEASE_TAG=release-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Forex-Calculator Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifacts to Release
      run: |
        for file in $(find artifacts -type f); do
          gh release upload ${{ env.RELEASE_TAG }} "$file"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
