name: Build and Release Forex Calculator

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        include:
          - os: ubuntu-20.04
            artifact_extension: tar.gz
          - os: macos-latest
            artifact_extension: zip
          - os: windows-latest
            artifact_extension: zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --------- Linux Section (Ubuntu 20.04) ---------
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build \
            libgl1-mesa-dev libglu1-mesa-dev cmake rsync \
            libxkbcommon-x11-0 libxkbcommon-dev patchelf

    - name: Download and Install Qt (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        wget https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
        chmod +x qt-unified-linux-x64-online.run
        echo "[Installer]
        AgreeToLicense=Yes
        InstallationPath=/opt/Qt" > qt_installer_script.qs
        sudo ./qt-unified-linux-x64-online.run --script qt_installer_script.qs || true
        echo "Qt installed at /opt/Qt"
        ls /opt/Qt || echo "Qt installation failed"

    - name: Verify Qt Installation (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        ls /opt/Qt/6.5.3/gcc_64 || echo "Qt not installed properly"
        ls /opt/Qt/6.5.3/gcc_64/lib/cmake || echo "CMake files not found"

    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        export PATH=/opt/Qt/6.5.3/gcc_64/bin:$PATH
        cmake -B "${{ github.workspace }}/build" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH=/opt/Qt/6.5.3/gcc_64/lib/cmake \
          -G "Ninja" \
          -S "${{ github.workspace }}"

    - name: Build Forex-Calculator (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: cmake --build "${{ github.workspace }}/build" --config Release

    - name: Package Forex-Calculator (Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        mkdir -p package
        cp "${{ github.workspace }}/build/Forex-Calculator" package/
        tar -czvf Forex-Calculator_ubuntu.tar.gz -C package .

    - name: Upload Linux Artifact
      if: matrix.os == 'ubuntu-20.04'
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_ubuntu
        path: Forex-Calculator_ubuntu.tar.gz

    # --------- macOS Section ---------
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ninja qt cmake

    - name: Configure CMake (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cmake -B "${{ github.workspace }}/build" \
          -DCMAKE_BUILD_TYPE=Release \
          -G "Ninja" \
          -S "${{ github.workspace }}"

    - name: Build Forex-Calculator (macOS)
      if: matrix.os == 'macos-latest'
      run: cmake --build "${{ github.workspace }}/build" --config Release

    - name: Package Forex-Calculator (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        mkdir -p package
        cp -R "${{ github.workspace }}/build/Forex-Calculator.app" package/
        zip -r Forex-Calculator_macos.zip package/

    - name: Upload macOS Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_macos
        path: Forex-Calculator_macos.zip

    # --------- Windows Section ---------
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install ninja -y
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install mingw -y
      shell: cmd

    - name: Install Qt (Windows)
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cmake -B "${{ github.workspace }}\\build" ^
          -DCMAKE_BUILD_TYPE=Release ^
          -G Ninja ^
          -DCMAKE_PREFIX_PATH=D:\\a\\Forex-Calculator\\Qt\\6.5.3\\mingw_64 ^
          -S "${{ github.workspace }}"
      shell: cmd

    - name: Build Forex-Calculator (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake --build "${{ github.workspace }}\\build" --config Release
      shell: cmd

    - name: Package Forex-Calculator (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir package
        cp "${{ github.workspace }}\\build\\Forex-Calculator.exe" package/
        D:\\a\\Forex-Calculator\\Qt\\6.5.3\\mingw_64\\bin\\windeployqt.exe package/Forex-Calculator.exe
        Compress-Archive -Path package -DestinationPath Forex-Calculator_windows.zip
      shell: pwsh

    - name: Upload Windows Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_windows
        path: Forex-Calculator_windows.zip

  # --------- Release Job ---------
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Generate Tag Name
      id: tag_name
      run: echo "RELEASE_TAG=release-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Forex-Calculator Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifacts to Release
      run: |
        for file in $(find artifacts -type f); do
          gh release upload ${{ env.RELEASE_TAG }} "$file"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
