name: Build and Release Forex Calculator

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  # ----------- Linux Build -----------
  build-linux:
    runs-on: ubuntu-22.04
    container: ubuntu:20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies (Linux)
      run: |
        apt update
        apt install -y ninja-build build-essential libgl1-mesa-dev libglu1-mesa-dev \
                        mesa-common-dev libxkbcommon-dev cmake fuse libfuse2 \
                        qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools patchelf
        wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        mv linuxdeployqt-continuous-x86_64.AppImage /usr/local/bin/linuxdeployqt

    - name: Configure CMake (Linux)
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja" -S .

    - name: Build Forex-Calculator (Linux)
      run: cmake --build build --config Release

    - name: Package with linuxdeployqt
      run: |
        mkdir -p package
        cp build/Forex-Calculator package/
        linuxdeployqt package/Forex-Calculator -appimage -bundle-non-qt-libs
        mv Forex-Calculator*.AppImage package/Forex-Calculator.AppImage
        tar -czvf Forex-Calculator_Linux.tar.gz -C package .

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_Linux
        path: Forex-Calculator_Linux.tar.gz

  # ----------- macOS Build -----------
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies (macOS)
      run: brew install ninja qt cmake

    - name: Configure CMake (macOS)
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja" -S .

    - name: Build Forex-Calculator (macOS)
      run: cmake --build build --config Release

    - name: Package Forex-Calculator (macOS)
      run: |
        mkdir -p package
        cp -R build/Forex-Calculator.app package/
        hdiutil create Forex-Calculator_macOS.dmg -srcfolder package/

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_macOS
        path: Forex-Calculator_macOS.dmg

  # ----------- Windows Build -----------
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies (Windows)
      run: |
        choco install ninja cmake mingw
      shell: cmd

    - name: Install Qt (Windows)
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'

    - name: Configure CMake (Windows)
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release ^
          -G Ninja ^
          -DCMAKE_PREFIX_PATH=D:\a\Forex-Calculator\Qt\6.5.3\mingw_64 ^
          -S .
      shell: cmd

    - name: Build Forex-Calculator (Windows)
      run: cmake --build build --config Release
      shell: cmd

    - name: Package Forex-Calculator (Windows)
      run: |
        mkdir package
        cp build/Forex-Calculator.exe package/
        D:\a\Forex-Calculator\Qt\6.5.3\mingw_64\bin\windeployqt.exe package/Forex-Calculator.exe
        Compress-Archive -Path package -DestinationPath Forex-Calculator_Windows.zip
      shell: pwsh

    - name: Upload Artifact (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_Windows
        path: Forex-Calculator_Windows.zip

  # ----------- Release Job -----------
  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List Downloaded Files
      run: ls -R artifacts

    - name: Generate Tag Name
      id: tag_name
      run: echo "RELEASE_TAG=release-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Forex-Calculator Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifacts to Release
      run: |
        for file in $(find artifacts -type f); do
          gh release upload ${{ env.RELEASE_TAG }} "$file"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
