name: Build and Release Static Binaries

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS, Windows]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ---------------------------
    # Ubuntu Section (Basic Qt Install)
    # ---------------------------
    - name: Install Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y ninja-build build-essential libgl1-mesa-dev libglu1-mesa-dev rsync qt6-base-dev qt6-tools-dev

    - name: Verify Qt Installation (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        ls /usr/lib/qt6/bin/ | grep windeployqt || echo "Qt tools not found"

    # ---------------------------
    # macOS Section (Basic Qt Install)
    # ---------------------------
    - name: Install Dependencies (macOS)
      if: matrix.os == 'macOS'
      run: brew install ninja qt

    - name: Verify Qt Installation (macOS)
      if: matrix.os == 'macOS'
      run: |
        ls $(brew --prefix qt)/bin/ | grep windeployqt || echo "Qt tools not found"

    # ---------------------------
    # Windows Section (Basic Qt Install)
    # ---------------------------
    - name: Install Dependencies (Windows)
      if: matrix.os == 'Windows'
      run: |
        choco install ninja cmake mingw
      shell: cmd

    - name: Install Qt (Windows)
      if: matrix.os == 'Windows'
      run: |
        choco install qt6-default qt6-tools
      shell: cmd

    - name: Verify Qt Installation (Windows)
      if: matrix.os == 'Windows'
      run: |
        dir "C:\Qt\" /s | findstr /i "windeployqt.exe"
      shell: cmd

    - name: Check for windeployqt Path (Windows)
      if: matrix.os == 'Windows'
      run: |
        $windeployqt = Get-ChildItem -Recurse -Filter windeployqt.exe "C:\Qt\" | Select-Object -First 1
        if (-not $windeployqt) {
          Write-Error "windeployqt.exe not found. Check Qt installation or PATH."
          exit 1
        }
        echo "windeployqt found at: $($windeployqt.FullName)"
      shell: pwsh
