name: Build and Release Forex Calculator

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: write  # Required for creating releases and uploading artifacts

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        include:
          - os: ubuntu-22.04
            artifact_extension: tar.gz
          - os: macos-12
            artifact_extension: dmg
          - os: windows-2022
            artifact_extension: zip

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ---------------------------
    # Ubuntu Section (AppImage)
    # ---------------------------
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt update
        sudo apt install -y ninja-build cmake qt6-base-dev qt6-tools-dev qt6-declarative-dev qt6-multimedia-dev \
          libgl1-mesa-dev libglu1-mesa-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-icccm4 patchelf libfuse2
        wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        sudo mv linuxdeployqt-continuous-x86_64.AppImage /usr/local/bin/linuxdeployqt

    - name: Configure CMake (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja

    - name: Build Forex-Calculator (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: cmake --build build

    - name: Package AppImage (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        mkdir -p package
        cp build/Forex-Calculator package/
        linuxdeployqt package/Forex-Calculator -appimage -bundle-non-qt-libs
        mv Forex-Calculator*.AppImage Forex-Calculator.AppImage

    - name: Upload AppImage Artifact
      if: matrix.os == 'ubuntu-22.04'
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_Ubuntu
        path: Forex-Calculator.AppImage

    # ---------------------------
    # macOS Section (DMG)
    # ---------------------------
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-12'
      run: brew install ninja cmake qt6

    - name: Configure and Build (macOS)
      if: matrix.os == 'macos-12'
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DQt6_DIR="/usr/local/opt/qt6"
        cmake --build build

    - name: Package DMG (macOS)
      if: matrix.os == 'macos-12'
      run: |
        mkdir -p package
        cp -R build/Forex-Calculator.app package/
        /usr/local/opt/qt6/bin/macdeployqt package/Forex-Calculator.app -dmg
        mv package/*.dmg Forex-Calculator_macos.dmg

    - name: Upload macOS Artifact
      if: matrix.os == 'macos-12'
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_macOS
        path: Forex-Calculator_macos.dmg

    # ---------------------------
    # Windows Section
    # ---------------------------
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-2022'
      run: |
        choco install ninja cmake mingw
      shell: cmd

    - name: Install Qt (Windows)
      if: matrix.os == 'windows-2022'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-2022'
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
      shell: cmd

    - name: Build Forex-Calculator (Windows)
      if: matrix.os == 'windows-2022'
      run: cmake --build build
      shell: cmd

    - name: Package (Windows)
      if: matrix.os == 'windows-2022'
      run: |
        mkdir package
        copy build\Forex-Calculator.exe package\
        windeployqt.exe package\Forex-Calculator.exe
        Compress-Archive -Path package -DestinationPath Forex-Calculator_windows.zip
      shell: pwsh

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Forex-Calculator_Windows
        path: Forex-Calculator_windows.zip

  # ---------------------------
  # Publish Section
  # ---------------------------
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true

    - name: Generate Release Tag
      run: echo "RELEASE_TAG=release-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Forex-Calculator ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
